<p style="font-family: Arial; font-size:3.75vw;color:purple; font-style:bold"><br>
pandas Exercise Notebook
</p><br>

# Exercise Notebook Instructions

### 1. Important: Only modify the cells which instruct you to modify them - leave "do not modify" cells alone.  

The code which tests your responses assumes you have run the startup/read-only code exactly.

### 2. Work through the notebook in order.

Some of the steps depend on previous, so you'll want to move through the notebook in order.

### 3. It is okay to use libraries.

You may find some questions are fairly straightforward to answer using built-in library functions.  That's totally okay - part of the point of these exercises is to familiarize you with the commonly used functions.

### 4. Seek help if stuck

If you get stuck, don't worry!  You can either review the videos/notebooks from this week, ask in the course forums, or look to the solutions for the correct answer.  BUT, be careful about looking to the solutions too quickly.  Struggling to get the right answer is an important part of the learning process.

In [4]:
import pandas as pd
import numpy as np
import os.path

In this exercise notebook you will have the opportunity to load the MovieLens database and perform additional analysis.

First let's load the data into a Pandas Dataframe:

In [5]:
# DO NOT MODIFY

# set here the relative path to the movielens folder
MOVIELENS="./movielens"

movies = pd.read_csv(os.path.join(MOVIELENS, 'movies.csv'), sep=',')
ratings = pd.read_csv(os.path.join(MOVIELENS, 'ratings.csv'), sep=',')

In [6]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [5]:
ratings.head()

   userId  movieId  rating   timestamp
0       1        2     3.5  1112486027
1       1       29     3.5  1112484676
2       1       32     3.5  1112484819
3       1       47     3.5  1112484727
4       1       50     3.5  1112484580

## Exercise 1: Find the Minimum Rating

Let's start by computing the minimum rating.

In the next cell, define the `min_rating` variable to be the minimum rating across all of the DataFrame:

In [7]:
min_rating = None
### BEGIN SOLUTION
min_rating = ratings['rating'].min()
min_rating
### END SOLUTION

0.5

In [8]:
# DO NOT MODIFY

assert isinstance(min_rating, np.float64), "Try again, make sure you are taking the min of just 1 column"
assert abs(min_rating - 0.5) < .01, "Try again, the minimum should be 0.5"

## Exercise 2: Find the Mean Rating of a Movie

The movie **Toy Story** has `movieId` 1. Find out the mean rating for Toy Story. For this exercise you just need to use the `ratings` DataFrame:

In [17]:
toy_story_rating = None
### BEGIN SOLUTION
toy_story_rating = ratings.loc[ratings['movieId'] == 1, 'rating'].mean()
toy_story_rating
### END SOLUTION

3.921239561324077

In [18]:
assert abs(toy_story_rating - 3.92) < 0.01, "Try again, select only the rows where the movieId is equal to 1"

## Exercise 3: Find the Most Common Rating

Next, find which rating is the most common.

In [19]:
rating_counts = None
### BEGIN SOLUTION
rating_counts = ratings['rating'].value_counts()
rating_counts
### END SOLUTION

4.0    5561926
3.0    4291193
5.0    2898660
3.5    2200156
4.5    1534824
2.0    1430997
2.5     883398
1.0     680732
1.5     279252
0.5     239125
Name: rating, dtype: int64

In [20]:
# DO NOT MODIFY

assert rating_counts.iloc[:1].index[0] == 4., "Print out rating_counts and try to understand what is wrong"

It is also interesting to inspect step by step what the statement above is doing:

    rating_counts.iloc[:1].index[0]

print all the intermediate stages of this expression, read the documentation of the functions used here.

## Exercise 4: Usage of the Index in pandas

In `numpy` the way to point to a specific entry in an array is by using its integer position. In `pandas` you can do the same with `iloc`, but you also have the option of defining a column in a DataFrame as an `index` and refer to rows using `index` labels instead of integer locations using `loc`.

For example in `rating_counts` defined above, the rating is the `index`, so we can reference a value either by its position or by its rating.

For example we can reference the 4th record either with `iloc` and its position or with `loc` and its label:

In [ ]:
rating_counts.iloc[3]

In [ ]:
rating_counts.loc[3.5]

## Exercise 5: Set an Index for the Movies DataFrame

Movies have one column `movieId` that is a natural way of uniquely identifying each row, when that is the case, it is useful to turn that into an index.

In [23]:
movies = movies.set_index("movieId")

In [26]:
movies.head()

,title,genres
movieId,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,Jumanji (1995),Adventure|Children|Fantasy
3,Grumpier Old Men (1995),Comedy|Romance
4,Waiting to Exhale (1995),Comedy|Drama|Romance
5,Father of the Bride Part II (1995),Comedy

In [24]:
ratings.head()

   userId  movieId  rating   timestamp
0       1        2     3.5  1112486027
1       1       29     3.5  1112484676
2       1       32     3.5  1112484819
3       1       47     3.5  1112484727
4       1       50     3.5  1112484580

Ratings instead do not have a row identifier, both `userId` and `movieId` reference records in other dataframes, therefore there is no good candidate for an index so we can just leave the default integer indexing.

## Exercise 6: Year with Maximum Standard Deviation in the Rating

First assignment is to find which year has the maximum standard deviation in the rating, **not** the maximum value of the standard deviation, but the year when it occurs.
You can use the `idxmax` method, look at its documentation on the pandas website, https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.idxmax.html

First we want to convert the timestamp into a datetime object:

In [27]:
# DO NOT MODIFY

ratings['parsed_time'] = pd.to_datetime(ratings['timestamp'], unit='s')

We can then access to datetime related fields through `dt`, for example:

In [29]:
ratings.parsed_time.dt.month

0            4
1            4
2            4
3            4
4            4
5            9
6            9
7            4
8            4
9            4
10           4
11           4
12           4
13           9
14           4
15           4
16           4
17           4
18           9
19           9
20           9
21           4
22           4
23           9
24           4
25           4
26           4
27           4
28           4
29           4
            ..
20000233    10
20000234    10
20000235    10
20000236    10
20000237    10
20000238    10
20000239    10
20000240    10
20000241    10
20000242    12
20000243    12
20000244    10
20000245    10
20000246    10
20000247    10
20000248    10
20000249    10
20000250    10
20000251    10
20000252    11
20000253    12
20000254    11
20000255    10
20000256    10
20000257    12
20000258    11
20000259    12
20000260    12
20000261    11
20000262    10
Name: parsed_time, Length: 20000263, dtype: int64

In [31]:
def find_year_with_max_std(ratings):
    """Function to find the year with the larger standard deviation in rating"""
    ### BEGIN SOLUTION
    ratings['year'] = ratings['parsed_time'].dt.year
    return(ratings.groupby('year')['rating'].std().idxmax())
    ### END SOLUTION
    
find_year_with_max_std(ratings)

1998

In [32]:
assert find_year_with_max_std(ratings) == 1998, "Wrong year identified, try again!"

## Advanced Exercise 1: Identify Popular Movies

*In the rest of the notebook, we will introduce new concepts not covered in class, this will challenge you to read additional pandas documentation.*

First we would like only to consider movies that have a significant number of ratings. This task is complicated by the fact that movies and ratings are in 2 different DataFrames and we want to filter the `movies` DataFrame based on a statistics on the `ratings` DataFrame.

First let's compute the number of ratings per movie:

In [7]:
number_of_ratings = ratings.movieId.value_counts()

In [34]:
number_of_ratings.head()

296    67310
356    66172
318    63366
593    63299
480    59715
Name: movieId, dtype: int64

Now we want to filter this pandas Series object and keep only the rows where the count is larger or equal to 100.
We don't want to pollute our analysis with movies with a tiny number of reviews:

In [8]:
number_of_ratings_of_popular_movies = None
### BEGIN SOLUTION
number_of_ratings_of_popular_movies = number_of_ratings[number_of_ratings >= 100]
### END SOLUTION
number_of_ratings_of_popular_movies.tail()

4208     100
865      100
51127    100
30867    100
80469    100
Name: movieId, dtype: int64

In [38]:
assert len(number_of_ratings_of_popular_movies) == 8546, "Try again, check that movies with 100 ratings are accepted"

Finally we want to use the `reindex` function to change the index of movies, this will create a new DataFrame with a new index that contains the movieId of only the most popular movies.

The value of all the rows of `movies` that have the same movieId will be copied over to the new `popular_movies` dataset, the rest will be discarded.

In [47]:
number_of_ratings_of_popular_movies.name = 'number_of_ratings'

In [58]:
len(movies)

27278

In [48]:
movies.join(number_of_ratings_of_popular_movies, how='inner')

,title,genres,number_of_ratings
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,49695
2,Jumanji (1995),Adventure|Children|Fantasy,22243
3,Grumpier Old Men (1995),Comedy|Romance,12735
4,Waiting to Exhale (1995),Comedy|Drama|Romance,2756
5,Father of the Bride Part II (1995),Comedy,12161
6,Heat (1995),Action|Crime|Thriller,23899
7,Sabrina (1995),Comedy|Romance,12961
8,Tom and Huck (1995),Adventure|Children,1415
9,Sudden Death (1995),Action,3960
10,GoldenEye (1995),Action|Adventure|Thriller,29005
11,"American President, The (1995)",Comedy|Drama|Romance,18162
12,Dracula: Dead and Loving It (1995),Comedy|Horror,3845
13,Balto (1995),Adventure|Animation|Children,1461
14,Nixon (1995),Drama,6022
15,Cutthroat Island (1995),Action|Adventure|Romance,2910
16,Casino (1995),Crime|Drama,17394
17,Sense and Sensibility (1995),Drama|Romance,20667
18,Four Rooms (1995),Comedy,5203
19,Ace Ventura: When Nature Calls (1995),Comedy,20938
20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller,4084
21,Get Shorty (1995),Comedy|Crime|Thriller,24116
22,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller,9928
23,Assassins (1995),Action|Crime|Thriller,4250
24,Powder (1995),Drama|Sci-Fi,7971
25,Leaving Las Vegas (1995),Drama|Romance,21553
26,Othello (1995),Drama,2755
27,Now and Then (1995),Children|Drama,1642
28,Persuasion (1995),Drama|Romance,3154
29,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,8520
30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Crime|Drama,1281
...,...,...,...
112897,"Expendables 3, The (2014)",Action|Adventure,162
112911,Hercules (2014),Action|Adventure,100
112940,"Most Wanted Man, A (2014)",Thriller,152
113275,"Hundred-Foot Journey, The (2014)",Drama,156
113348,Teenage Mutant Ninja Turtles (2014),Action|Adventure|Comedy,172
113378,"Giver, The (2014)",Drama|Sci-Fi,150
113573,Sin City: A Dame to Kill For (2014),Action|Crime|Thriller,251
113741,Coherence (2013),Drama|Mystery|Sci-Fi|Thriller,130
114060,"Drop, The (2014)",Crime|Drama|Thriller,109
114180,"Maze Runner, The (2014)",Action|Mystery|Sci-Fi,436
114662,American Sniper (2014),Action|War,256
114795,Dracula Untold (2014),Action|Drama|Fantasy,124
114935,Predestination (2014),Sci-Fi|Thriller,318
115149,John Wick (2014),Action|Thriller,292
115170,"Judge, The (2014)",Drama,127
115210,Fury (2014),Action|Drama|War,379
115231,St. Vincent (2014),Comedy,131
115569,Nightcrawler (2014),Crime|Drama|Thriller,609
115617,Big Hero 6 (2014),Action|Animation|Comedy,448
116161,Foxcatcher (2014),Drama,177
116797,The Imitation Game (2014),Drama|Thriller,759
116823,The Hunger Games: Mockingjay - Part 1 (2014),Adventure|Sci-Fi|Thriller,567
116977,Dumb and Dumber To (2014),Comedy,145
117176,"Theory of Everything, The (2014)",Drama|Romance,349
117590,Horrible Bosses 2 (2014),Comedy|Crime,102
118696,The Hobbit: The Battle of the Five Armies (2014),Adventure|Fantasy,538
118900,Wild (2014),Drama,109
118997,Into the Woods (2014),Children|Comedy|Fantasy|Musical,129
119141,The Interview (2014),Action|Comedy,375
119145,Kingsman: The Secret Service (2015),Action|Adventure|Comedy|Crime,159

In [52]:
?pd.DataFrame.reindex

In [9]:
# Reindexing by passing a new index will match rows of old inidicies with the new ones
all_popular_movies = movies.reindex(number_of_ratings_of_popular_movies.index)
all_popular_movies

,movieId,title,genres
296,299.0,Priest (1994),Drama
356,360.0,I Love Trouble (1994),Action|Comedy
318,321.0,Strawberry and Chocolate (Fresa y chocolate) (...,Drama
593,599.0,"Wild Bunch, The (1969)",Adventure|Western
480,484.0,Lassie (1994),Adventure|Children
260,263.0,Ladybird Ladybird (1994),Drama
110,112.0,Rumble in the Bronx (Hont faan kui) (1995),Action|Adventure|Comedy|Crime
589,595.0,Beauty and the Beast (1991),Animation|Children|Fantasy|Musical|Romance|IMAX
2571,2657.0,"Rocky Horror Picture Show, The (1975)",Comedy|Horror|Musical|Sci-Fi
527,531.0,"Secret Garden, The (1993)",Children|Drama
1,2.0,Jumanji (1995),Adventure|Children|Fantasy
457,461.0,Go Fish (1994),Drama|Romance
150,152.0,"Addiction, The (1995)",Drama|Horror
780,793.0,My Life and Times With Antonin Artaud (En comp...,Drama
50,51.0,Guardian Angel (1994),Action|Drama|Thriller
1210,1237.0,"Seventh Seal, The (Sjunde inseglet, Det) (1957)",Drama
592,598.0,Window to Paris (Okno v Parizh) (1994),Comedy|Fantasy
1196,1222.0,Full Metal Jacket (1987),Drama|War
2858,2944.0,"Dirty Dozen, The (1967)",Action|Drama|War
32,33.0,Wings of Courage (1995),Adventure|Romance|IMAX
590,596.0,Pinocchio (1940),Animation|Children|Fantasy|Musical
1198,1224.0,Henry V (1989),Action|Drama|Romance|War
608,614.0,Loaded (1994),Drama|Thriller
47,48.0,Pocahontas (1995),Animation|Children|Drama|Musical|Romance
380,384.0,Bad Company (1995),Action|Crime|Drama
588,594.0,Snow White and the Seven Dwarfs (1937),Animation|Children|Drama|Fantasy|Musical
377,381.0,When a Man Loves a Woman (1994),Drama|Romance
1270,1299.0,"Killing Fields, The (1984)",Drama|War
858,874.0,Killer: A Journal of Murder (1995),Crime|Drama
2959,3046.0,Incredibly True Adventure of Two Girls in Love...,Comedy|Romance
...,...,...,...
7561,7924.0,Stray Dog (Nora inu) (1949),Drama|Film-Noir|Thriller
8040,8723.0,Warriors (Guerreros) (2002),Adventure|Drama|War
1891,1975.0,Friday the 13th Part 2 (1981),Horror
7753,8335.0,Make Way for Tomorrow (1937),Drama
8987,26690.0,Shipwrecked (a.k.a. Haakon Haakonsen) (1990),Adventure|Children
6173,6272.0,Eye of God (1997),Drama
4289,4384.0,Lumumba (2000),Drama
27784,NaN,NaN,NaN
1181,1207.0,To Kill a Mockingbird (1962),Drama
44301,NaN,NaN,NaN
3874,3968.0,Bedazzled (2000),Comedy
3568,3659.0,Quatermass 2 (Enemy from Space) (1957),Sci-Fi|Thriller
27456,NaN,NaN,NaN
6616,6726.0,"Song for Martin, A (Sång för Martin, En) (2001)",Drama
7615,8010.0,"Power of One, The (1992)",Drama
6293,6401.0,Rio Lobo (1970),Adventure|Romance|War|Western
8201,8884.0,"Man with One Red Shoe, The (1985)",Comedy|Thriller
687,699.0,To Cross the Rubicon (1991),Drama
71878,NaN,NaN,NaN
5256,5353.0,Butterflies Are Free (1972),Comedy|Drama
59915,NaN,NaN,NaN
112911,NaN,NaN,NaN
26746,128604.0,Knight of Cups (2015),Drama
56336,NaN,NaN,NaN
6390,6500.0,"Satanic Rites of Dracula, The (1974)",Horror
4208,4303.0,Sordid Lives (2000),Comedy
865,881.0,First Kid (1996),Children|Comedy
51127,NaN,NaN,NaN
30867,NaN,NaN,NaN
80469,NaN,NaN,NaN

## Advanced Exercise 2: Data Cleaning

Everytime we perform a reindexing operation, `pandas` will create a row for every value of the new index, even if it doesn't exist in the original data structure, and it will mark those data as missing with `NaN` (Not A Number).

Always check if reindexing generated invalid data:

In [60]:
all_popular_movies.isnull().sum()

title     0
genres    0
dtype: int64

In the next cell we want to drop the invalid data, look for a `pandas` function that performs that operation (it starts with "drop"!).

In [10]:
popular_movies = None
### BEGIN SOLUTION
popular_movies = all_popular_movies.dropna()
popular_movies
### END SOLUTION

,movieId,title,genres
296,299.0,Priest (1994),Drama
356,360.0,I Love Trouble (1994),Action|Comedy
318,321.0,Strawberry and Chocolate (Fresa y chocolate) (...,Drama
593,599.0,"Wild Bunch, The (1969)",Adventure|Western
480,484.0,Lassie (1994),Adventure|Children
260,263.0,Ladybird Ladybird (1994),Drama
110,112.0,Rumble in the Bronx (Hont faan kui) (1995),Action|Adventure|Comedy|Crime
589,595.0,Beauty and the Beast (1991),Animation|Children|Fantasy|Musical|Romance|IMAX
2571,2657.0,"Rocky Horror Picture Show, The (1975)",Comedy|Horror|Musical|Sci-Fi
527,531.0,"Secret Garden, The (1993)",Children|Drama
1,2.0,Jumanji (1995),Adventure|Children|Fantasy
457,461.0,Go Fish (1994),Drama|Romance
150,152.0,"Addiction, The (1995)",Drama|Horror
780,793.0,My Life and Times With Antonin Artaud (En comp...,Drama
50,51.0,Guardian Angel (1994),Action|Drama|Thriller
1210,1237.0,"Seventh Seal, The (Sjunde inseglet, Det) (1957)",Drama
592,598.0,Window to Paris (Okno v Parizh) (1994),Comedy|Fantasy
1196,1222.0,Full Metal Jacket (1987),Drama|War
2858,2944.0,"Dirty Dozen, The (1967)",Action|Drama|War
32,33.0,Wings of Courage (1995),Adventure|Romance|IMAX
590,596.0,Pinocchio (1940),Animation|Children|Fantasy|Musical
1198,1224.0,Henry V (1989),Action|Drama|Romance|War
608,614.0,Loaded (1994),Drama|Thriller
47,48.0,Pocahontas (1995),Animation|Children|Drama|Musical|Romance
380,384.0,Bad Company (1995),Action|Crime|Drama
588,594.0,Snow White and the Seven Dwarfs (1937),Animation|Children|Drama|Fantasy|Musical
377,381.0,When a Man Loves a Woman (1994),Drama|Romance
1270,1299.0,"Killing Fields, The (1984)",Drama|War
858,874.0,Killer: A Journal of Murder (1995),Crime|Drama
2959,3046.0,Incredibly True Adventure of Two Girls in Love...,Comedy|Romance
...,...,...,...
4691,4787.0,Little Man Tate (1991),Drama
6211,6310.0,Memories of Me (1988),Comedy|Drama
4917,5013.0,Gosford Park (2001),Comedy|Drama|Mystery
2896,2982.0,"Guardian, The (1990)",Horror|Thriller
6020,6119.0,Santa Claus Is a Stinker (Le Père Noël est une...,Comedy
6409,6519.0,Fun with Dick and Jane (1977),Comedy
7391,7615.0,Desert Hearts (1985),Drama
794,807.0,"Rendezvous in Paris (Rendez-vous de Paris, Les...",Comedy|Romance
3940,4034.0,Traffic (2000),Crime|Drama|Thriller
6257,6356.0,Gunfight at the O.K. Corral (1957),Western
7561,7924.0,Stray Dog (Nora inu) (1949),Drama|Film-Noir|Thriller
8040,8723.0,Warriors (Guerreros) (2002),Adventure|Drama|War
1891,1975.0,Friday the 13th Part 2 (1981),Horror
7753,8335.0,Make Way for Tomorrow (1937),Drama
8987,26690.0,Shipwrecked (a.k.a. Haakon Haakonsen) (1990),Adventure|Children
6173,6272.0,Eye of God (1997),Drama
4289,4384.0,Lumumba (2000),Drama
1181,1207.0,To Kill a Mockingbird (1962),Drama
3874,3968.0,Bedazzled (2000),Comedy
3568,3659.0,Quatermass 2 (Enemy from Space) (1957),Sci-Fi|Thriller
6616,6726.0,"Song for Martin, A (Sång för Martin, En) (2001)",Drama
7615,8010.0,"Power of One, The (1992)",Drama
6293,6401.0,Rio Lobo (1970),Adventure|Romance|War|Western
8201,8884.0,"Man with One Red Shoe, The (1985)",Comedy|Thriller
687,699.0,To Cross the Rubicon (1991),Drama
5256,5353.0,Butterflies Are Free (1972),Comedy|Drama
26746,128604.0,Knight of Cups (2015),Drama
6390,6500.0,"Satanic Rites of Dracula, The (1974)",Horror
4208,4303.0,Sordid Lives (2000),Comedy
865,881.0,First Kid (1996),Children|Comedy

In [ ]:
assert len(popular_movies) == 7847, "Try again, check the documentation of the function you used"

## Advanced Exercise 3: Filter by Genre

Let's implement a general function that filters movies by genres:

In [11]:
def filter_by_genre(input_movies, genre):
    """Return only movies of a specific genre"""
    ### BEGIN SOLUTION
    return input_movies[input_movies['genres'].str.contains(genre, case=False)]
    ### END SOLUTION

Then let's apply it to the `popular_movies` dataset to retain only the "Fantasy" movies:

In [12]:
fantasy_movies = filter_by_genre(popular_movies, "Fantasy")
fantasy_movies

,movieId,title,genres
589,595.0,Beauty and the Beast (1991),Animation|Children|Fantasy|Musical|Romance|IMAX
1,2.0,Jumanji (1995),Adventure|Children|Fantasy
592,598.0,Window to Paris (Okno v Parizh) (1994),Comedy|Fantasy
590,596.0,Pinocchio (1940),Animation|Children|Fantasy|Musical
588,594.0,Snow White and the Seven Dwarfs (1937),Animation|Children|Drama|Fantasy|Musical
349,353.0,"Crow, The (1994)",Action|Crime|Fantasy|Thriller
1213,1241.0,Dead Alive (Braindead) (1992),Comedy|Fantasy|Horror
4973,5069.0,Escaflowne: The Movie (Escaflowne) (2000),Action|Adventure|Animation|Drama|Fantasy
2329,2414.0,Young Sherlock Holmes (1985),Action|Adventure|Children|Fantasy|Mystery|Thri...
4995,5091.0,The Man from Acapulco (1973),Action|Comedy|Fantasy|Romance
1968,2052.0,Hocus Pocus (1993),Children|Comedy|Fantasy|Horror
3147,3234.0,Train Ride to Hollywood (1975),Comedy|Fantasy|Musical
8961,26631.0,Alice (Neco z Alenky) (1988),Animation|Fantasy|Mystery
4011,4105.0,"Evil Dead, The (1981)",Fantasy|Horror|Thriller
1247,1275.0,Highlander (1986),Action|Adventure|Fantasy
2054,2138.0,Watership Down (1978),Adventure|Animation|Children|Drama|Fantasy
553,558.0,"Pagemaster, The (1994)",Action|Adventure|Animation|Children|Fantasy
653,661.0,James and the Giant Peach (1996),Adventure|Animation|Children|Fantasy|Musical
1233,1261.0,Evil Dead II (Dead by Dawn) (1987),Action|Comedy|Fantasy|Horror
8368,25771.0,"Andalusian Dog, An (Chien andalou, Un) (1929)",Fantasy
1376,1409.0,Michael (1996),Comedy|Drama|Fantasy|Romance
1250,1278.0,Young Frankenstein (1974),Comedy|Fantasy
6934,7046.0,"Witches of Eastwick, The (1987)",Comedy|Fantasy|Horror|Thriller
5669,5768.0,Modern Problems (1981),Comedy|Fantasy
2019,2103.0,Tall Tale (1995),Adventure|Children|Fantasy|Western
186,188.0,"Prophecy, The (1995)",Fantasy|Horror|Mystery
2003,2087.0,Peter Pan (1953),Animation|Children|Fantasy|Musical
529,533.0,"Shadow, The (1994)",Action|Adventure|Fantasy|Mystery
1597,1654.0,FairyTale: A True Story (1997),Children|Drama|Fantasy
2105,2189.0,I Married A Strange Person! (1997),Animation|Comedy|Fantasy|Sci-Fi
...,...,...,...
26663,128279.0,Sylvia and the Ghost (1946),Comedy|Fantasy|Romance
1153,1176.0,"Double Life of Veronique, The (Double Vie de V...",Drama|Fantasy|Romance
4944,5040.0,Conan the Destroyer (1984),Action|Adventure|Fantasy
6749,6859.0,"Devil and Daniel Webster, The (All That Money ...",Drama|Fantasy
775,788.0,"Nutty Professor, The (1996)",Comedy|Fantasy|Romance|Sci-Fi
26199,125996.0,The Black Devil (1905),Comedy|Fantasy
4790,4886.0,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy
6805,6916.0,"Magic Sword, The (1962)",Drama|Fantasy
8726,26258.0,"Topo, El (1970)",Fantasy|Western
2914,3000.0,Princess Mononoke (Mononoke-hime) (1997),Action|Adventure|Animation|Drama|Fantasy
4078,4172.0,Simon Magus (1999),Drama|Fantasy|Mystery|Romance
5061,5157.0,"Church, The (Chiesa, La) (1989)",Drama|Fantasy|Horror
7328,7454.0,Van Helsing (2004),Action|Adventure|Fantasy|Horror
4831,4927.0,"Last Wave, The (1977)",Fantasy|Mystery|Thriller
7190,7302.0,"Thief of Bagdad, The (1924)",Action|Adventure|Fantasy
4897,4993.0,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy
6747,6857.0,Ninja Scroll (Jûbei ninpûchô) (1995),Action|Adventure|Animation|Fantasy
3922,4016.0,"Emperor's New Groove, The (2000)",Adventure|Animation|Children|Comedy|Fantasy
797,810.0,Kazaam (1996),Children|Comedy|Fantasy
25943,123553.0,In the Name of the King III (2014),Action|Adventure|Drama|Fantasy
4819,4915.0,"Beastmaster, The (1982)",Action|Adventure|Fantasy
26394,126927.0,The Heart of the World (2000),Drama|Fantasy
4884,4980.0,Bill & Ted's Bogus Journey (1991),Adventure|Comedy|Fantasy|Sci-Fi
8868,26483.0,Rock & Rule (1983),Animation|Fantasy|Musical|Sci-Fi
4777,4873.0,Waking Life (2001),Animation|Drama|Fantasy
5366,5463.0,Reign of Fire (2002),Action|Adventure|Fantasy
3351,3440.0,Teenage Mutant Ninja Turtles III (1993),Action|Adventure|Children|Comedy|Fantasy
2008,2092.0,"Return of Jafar, The (1994)",Adventure|Animation|Children|Fantasy|Musical|R...
7847,8492.0,"Christmas Carol, A (Scrooge) (1951)",Drama|Fantasy
7613,8008.0,Brigadoon (1954),Fantasy|Musical|Romance

In [63]:
assert len(fantasy_movies) == 382, """Try again, Make sure you are filtering the popular movies"""

AssertionError: Try again, Make sure you are filtering the popular movies

## Advanced Exercise 4: Join Movies and Ratings

Let's create a single `DataFrame` that contains both titles and mean ratings of the popular fantasy movies.

Titles are only available in the `movies` `DataFrame`, while ratings in the `ratings` `DataFrame`, we would like to create a single DataFrame that includes Title.

Create the `mean_ratings` variable by computing the mean rating for each movie:

In [16]:
mean_ratings = None
### BEGIN SOLUTION
mean_ratings = ratings.groupby('movieId')['rating'].mean()
### END SOLUTION

In this case we don't even need to use a join operation, we can just create a new column in the `fantasy_movies` DataFrame. This will automatically match the index of `mean_ratings` with the index of `fantasy_movies` and attach to each movie its rating. Ratings for movies that are not in the `fantasy_movies` DataFrame are discarded.

The recommended way of creating columns in the recent versions of `pandas` is through the `assign` function, read its documentation!

In [67]:
fantasy_movies.assign?

In [18]:
fantasy_movies_with_ratings = fantasy_movies.assign(rating = mean_ratings)
fantasy_movies_with_ratings

,movieId,title,genres,rating
589,595.0,Beauty and the Beast (1991),Animation|Children|Fantasy|Musical|Romance|IMAX,3.931954
1,2.0,Jumanji (1995),Adventure|Children|Fantasy,3.921240
592,598.0,Window to Paris (Okno v Parizh) (1994),Comedy|Fantasy,3.402365
590,596.0,Pinocchio (1940),Animation|Children|Fantasy|Musical,3.728465
588,594.0,Snow White and the Seven Dwarfs (1937),Animation|Children|Drama|Fantasy|Musical,3.680871
349,353.0,"Crow, The (1994)",Action|Crime|Fantasy|Thriller,3.660309
1213,1241.0,Dead Alive (Braindead) (1992),Comedy|Fantasy|Horror,4.183633
4973,5069.0,Escaflowne: The Movie (Escaflowne) (2000),Action|Adventure|Animation|Drama|Fantasy,4.197072
2329,2414.0,Young Sherlock Holmes (1985),Action|Adventure|Children|Fantasy|Mystery|Thri...,4.151208
4995,5091.0,The Man from Acapulco (1973),Action|Comedy|Fantasy|Romance,3.919748
1968,2052.0,Hocus Pocus (1993),Children|Comedy|Fantasy|Horror,3.828646
3147,3234.0,Train Ride to Hollywood (1975),Comedy|Fantasy|Musical,3.982661
8961,26631.0,Alice (Neco z Alenky) (1988),Animation|Fantasy|Mystery,3.908572
4011,4105.0,"Evil Dead, The (1981)",Fantasy|Horror|Thriller,4.042147
1247,1275.0,Highlander (1986),Action|Adventure|Fantasy,4.073889
2054,2138.0,Watership Down (1978),Adventure|Animation|Children|Drama|Fantasy,2.702726
553,558.0,"Pagemaster, The (1994)",Action|Adventure|Animation|Children|Fantasy,3.697500
653,661.0,James and the Giant Peach (1996),Adventure|Animation|Children|Fantasy|Musical,3.216848
1233,1261.0,Evil Dead II (Dead by Dawn) (1987),Action|Comedy|Fantasy|Horror,4.139730
8368,25771.0,"Andalusian Dog, An (Chien andalou, Un) (1929)",Fantasy,3.752071
1376,1409.0,Michael (1996),Comedy|Drama|Fantasy|Romance,3.494617
1250,1278.0,Young Frankenstein (1974),Comedy|Fantasy,4.110051
6934,7046.0,"Witches of Eastwick, The (1987)",Comedy|Fantasy|Horror|Thriller,3.143747
5669,5768.0,Modern Problems (1981),Comedy|Fantasy,3.787622
2019,2103.0,Tall Tale (1995),Adventure|Children|Fantasy|Western,4.274180
186,188.0,"Prophecy, The (1995)",Fantasy|Horror|Mystery,2.891731
2003,2087.0,Peter Pan (1953),Animation|Children|Fantasy|Musical,3.243839
529,533.0,"Shadow, The (1994)",Action|Adventure|Fantasy|Mystery,3.850758
1597,1654.0,FairyTale: A True Story (1997),Children|Drama|Fantasy,3.320401
2105,2189.0,I Married A Strange Person! (1997),Animation|Comedy|Fantasy|Sci-Fi,3.324831
...,...,...,...,...
26663,128279.0,Sylvia and the Ghost (1946),Comedy|Fantasy|Romance,3.669065
1153,1176.0,"Double Life of Veronique, The (Double Vie de V...",Drama|Fantasy|Romance,3.266187
4944,5040.0,Conan the Destroyer (1984),Action|Adventure|Fantasy,2.079137
6749,6859.0,"Devil and Daniel Webster, The (All That Money ...",Drama|Fantasy,3.489209
775,788.0,"Nutty Professor, The (1996)",Comedy|Fantasy|Romance|Sci-Fi,2.905797
26199,125996.0,The Black Devil (1905),Comedy|Fantasy,3.203008
4790,4886.0,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy,2.916667
6805,6916.0,"Magic Sword, The (1962)",Drama|Fantasy,3.128788
8726,26258.0,"Topo, El (1970)",Fantasy|Western,3.538168
2914,3000.0,Princess Mononoke (Mononoke-hime) (1997),Action|Adventure|Animation|Drama|Fantasy,2.348837
4078,4172.0,Simon Magus (1999),Drama|Fantasy|Mystery|Romance,3.130952
5061,5157.0,"Church, The (Chiesa, La) (1989)",Drama|Fantasy|Horror,3.077869
7328,7454.0,Van Helsing (2004),Action|Adventure|Fantasy|Horror,3.704167
4831,4927.0,"Last Wave, The (1977)",Fantasy|Mystery|Thriller,2.098291
7190,7302.0,"Thief of Bagdad, The (1924)",Action|Adventure|Fantasy,3.542735
4897,4993.0,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy,2.693966
6747,6857.0,Ninja Scroll (Jûbei ninpûchô) (1995),Action|Adventure|Animation|Fantasy,3.219828
3922,4016.0,"Emperor's New Groove, The (2000)",Adventure|Animation|Children|Comedy|Fantasy,2.452174
797,810.0,Kazaam (1996),Children|Comedy|Fantasy,3.364035
25943,123553.0,In the Name of the King III (2014),Action|Adventure|Drama|Fantasy,3.642857
4819,4915.0,"Beastmaster, The (1982)",Action|Adventure|Fantasy,3.236364
26394,126927.0,The Heart of the World (2000),Drama|Fantasy,3.477064
4884,4980.0,Bill & Ted's Bogus Journey (1991),Adventure|Comedy|Fantasy|Sci-Fi,3.435780
8868,26483.0,Rock & Rule (1983),Animation|Fantasy|Musical|Sci-Fi,2.824074
4777,4873.0,Waking Life (2001),Animation|Drama|Fantasy,3.353774
5366,5463.0,Reign of Fire (2002),Action|Adventure|Fantasy,2.393204
3351,3440.0,Teenage Mutant Ninja Turtles III (1993),Action|Adventure|Children|Comedy|Fantasy,2.883495
2008,2092.0,"Return of Jafar, The (1994)",Adventure|Animation|Children|Fantasy|Musical|R...,2.601942
7847,8492.0,"Christmas Carol, A (Scrooge) (1951)",Drama|Fantasy,3.240196
7613,8008.0,Brigadoon (1954),Fantasy|Musical|Romance,3.274510

In [19]:
fantasy_movies.join(mean_ratings, how='inner')

,movieId,title,genres,rating
589,595.0,Beauty and the Beast (1991),Animation|Children|Fantasy|Musical|Romance|IMAX,3.931954
1,2.0,Jumanji (1995),Adventure|Children|Fantasy,3.921240
592,598.0,Window to Paris (Okno v Parizh) (1994),Comedy|Fantasy,3.402365
590,596.0,Pinocchio (1940),Animation|Children|Fantasy|Musical,3.728465
588,594.0,Snow White and the Seven Dwarfs (1937),Animation|Children|Drama|Fantasy|Musical,3.680871
349,353.0,"Crow, The (1994)",Action|Crime|Fantasy|Thriller,3.660309
1213,1241.0,Dead Alive (Braindead) (1992),Comedy|Fantasy|Horror,4.183633
4973,5069.0,Escaflowne: The Movie (Escaflowne) (2000),Action|Adventure|Animation|Drama|Fantasy,4.197072
2329,2414.0,Young Sherlock Holmes (1985),Action|Adventure|Children|Fantasy|Mystery|Thri...,4.151208
4995,5091.0,The Man from Acapulco (1973),Action|Comedy|Fantasy|Romance,3.919748
1968,2052.0,Hocus Pocus (1993),Children|Comedy|Fantasy|Horror,3.828646
3147,3234.0,Train Ride to Hollywood (1975),Comedy|Fantasy|Musical,3.982661
8961,26631.0,Alice (Neco z Alenky) (1988),Animation|Fantasy|Mystery,3.908572
4011,4105.0,"Evil Dead, The (1981)",Fantasy|Horror|Thriller,4.042147
1247,1275.0,Highlander (1986),Action|Adventure|Fantasy,4.073889
2054,2138.0,Watership Down (1978),Adventure|Animation|Children|Drama|Fantasy,2.702726
553,558.0,"Pagemaster, The (1994)",Action|Adventure|Animation|Children|Fantasy,3.697500
653,661.0,James and the Giant Peach (1996),Adventure|Animation|Children|Fantasy|Musical,3.216848
1233,1261.0,Evil Dead II (Dead by Dawn) (1987),Action|Comedy|Fantasy|Horror,4.139730
8368,25771.0,"Andalusian Dog, An (Chien andalou, Un) (1929)",Fantasy,3.752071
1376,1409.0,Michael (1996),Comedy|Drama|Fantasy|Romance,3.494617
1250,1278.0,Young Frankenstein (1974),Comedy|Fantasy,4.110051
6934,7046.0,"Witches of Eastwick, The (1987)",Comedy|Fantasy|Horror|Thriller,3.143747
5669,5768.0,Modern Problems (1981),Comedy|Fantasy,3.787622
2019,2103.0,Tall Tale (1995),Adventure|Children|Fantasy|Western,4.274180
186,188.0,"Prophecy, The (1995)",Fantasy|Horror|Mystery,2.891731
2003,2087.0,Peter Pan (1953),Animation|Children|Fantasy|Musical,3.243839
529,533.0,"Shadow, The (1994)",Action|Adventure|Fantasy|Mystery,3.850758
1597,1654.0,FairyTale: A True Story (1997),Children|Drama|Fantasy,3.320401
2105,2189.0,I Married A Strange Person! (1997),Animation|Comedy|Fantasy|Sci-Fi,3.324831
...,...,...,...,...
26663,128279.0,Sylvia and the Ghost (1946),Comedy|Fantasy|Romance,3.669065
1153,1176.0,"Double Life of Veronique, The (Double Vie de V...",Drama|Fantasy|Romance,3.266187
4944,5040.0,Conan the Destroyer (1984),Action|Adventure|Fantasy,2.079137
6749,6859.0,"Devil and Daniel Webster, The (All That Money ...",Drama|Fantasy,3.489209
775,788.0,"Nutty Professor, The (1996)",Comedy|Fantasy|Romance|Sci-Fi,2.905797
26199,125996.0,The Black Devil (1905),Comedy|Fantasy,3.203008
4790,4886.0,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy,2.916667
6805,6916.0,"Magic Sword, The (1962)",Drama|Fantasy,3.128788
8726,26258.0,"Topo, El (1970)",Fantasy|Western,3.538168
2914,3000.0,Princess Mononoke (Mononoke-hime) (1997),Action|Adventure|Animation|Drama|Fantasy,2.348837
4078,4172.0,Simon Magus (1999),Drama|Fantasy|Mystery|Romance,3.130952
5061,5157.0,"Church, The (Chiesa, La) (1989)",Drama|Fantasy|Horror,3.077869
7328,7454.0,Van Helsing (2004),Action|Adventure|Fantasy|Horror,3.704167
4831,4927.0,"Last Wave, The (1977)",Fantasy|Mystery|Thriller,2.098291
7190,7302.0,"Thief of Bagdad, The (1924)",Action|Adventure|Fantasy,3.542735
4897,4993.0,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy,2.693966
6747,6857.0,Ninja Scroll (Jûbei ninpûchô) (1995),Action|Adventure|Animation|Fantasy,3.219828
3922,4016.0,"Emperor's New Groove, The (2000)",Adventure|Animation|Children|Comedy|Fantasy,2.452174
797,810.0,Kazaam (1996),Children|Comedy|Fantasy,3.364035
25943,123553.0,In the Name of the King III (2014),Action|Adventure|Drama|Fantasy,3.642857
4819,4915.0,"Beastmaster, The (1982)",Action|Adventure|Fantasy,3.236364
26394,126927.0,The Heart of the World (2000),Drama|Fantasy,3.477064
4884,4980.0,Bill & Ted's Bogus Journey (1991),Adventure|Comedy|Fantasy|Sci-Fi,3.435780
8868,26483.0,Rock & Rule (1983),Animation|Fantasy|Musical|Sci-Fi,2.824074
4777,4873.0,Waking Life (2001),Animation|Drama|Fantasy,3.353774
5366,5463.0,Reign of Fire (2002),Action|Adventure|Fantasy,2.393204
3351,3440.0,Teenage Mutant Ninja Turtles III (1993),Action|Adventure|Children|Comedy|Fantasy,2.883495
2008,2092.0,"Return of Jafar, The (1994)",Adventure|Animation|Children|Fantasy|Musical|R...,2.601942
7847,8492.0,"Christmas Carol, A (Scrooge) (1951)",Drama|Fantasy,3.240196
7613,8008.0,Brigadoon (1954),Fantasy|Musical|Romance,3.274510

In [ ]:
fantasy_movies_with_ratings.head()

In [ ]:
assert fantasy_movies_with_ratings.loc[7842].title.startswith("Dune"), "Try again, missing or wrong title"

In [ ]:
assert abs(fantasy_movies_with_ratings.loc[7842].rating - 3.56) < 0.01 , "Try again, missing or wrong rating"

## Advanced Exercise 5: Find the Highest Rated Fantasy Movie

Again we need to find the index where a column is max, in this case rating:

In [21]:
index_of_max_rating = None
### BEGIN SOLUTION
index_of_max_rating = fantasy_movies_with_ratings['rating'].idxmax()
index_of_max_rating
### END SOLUTION

2019

In [22]:
highest_rated_fantasy_movie = fantasy_movies_with_ratings.loc[index_of_max_rating]
highest_rated_fantasy_movie

movieId                                  2103
title                        Tall Tale (1995)
genres     Adventure|Children|Fantasy|Western
rating                                4.27418
Name: 2019, dtype: object

In [29]:
is_princess = fantasy_movies_with_ratings['title'].str.startswith('Princess')
fantasy_movies_with_ratings.loc[is_princess]

,movieId,title,genres,rating
1172,1197.0,"Princess Bride, The (1987)",Action|Adventure|Comedy|Fantasy|Romance,4.154011
2914,3000.0,Princess Mononoke (Mononoke-hime) (1997),Action|Adventure|Animation|Drama|Fantasy,2.348837

In [ ]:
assert highest_rated_fantasy_movie.title.startswith("Princess"), "Try again"